### ISSUE TITLE
Something broke

### ISSUE THREAD

**Issue by Sonic4Tails** [dancepartyonline/patcher#2]
error

DanceParty Patcher
INFO: DOL file loadded successfully.
Traceback (most recent call last):
  File "C:\Users\purpe\Downloads\patcher-main\patcher.py", line 88, in <module>
    patch_exec(dol_path, dol_path)
  File "C:\Users\purpe\Downloads\patcher-main\patcher.py", line 58, in patch_exec
    for key, value in SERVERS.items():
                      ^^^^^^^
UnboundLocalError: cannot access local variable 'SERVERS' where it is not associated with a value

**Comment by chaeyan** [comment]
please try it again
